"use client";

import { useMemo, useState } from "react";

type Room = "2LDK" | "3LDK";
type Stock = "used" | "new";

const areaData = [
  { id:"sekime", rank:"01", name:"关目高殿 / 关目", jp:"関目高殿・関目", tag:"综合首选", color:"mint", commute:16, route:"京阪本线直达", umeda:10, scores:[9.4,9.0,9.2,7.2], price:{used:{"2LDK":[3900,5200],"3LDK":[4300,5900]},new:{"2LDK":[5100,6200],"3LDK":[5800,7500]}}, trend:12, sample:"关目高殿站步行 10 分钟内；中古限定 2016 年以后，约 55–75㎡。", life:"四站四线可用，去东梅田与门真市都不绕路；成熟住宅区，日常生活安静但不闭塞。", commerce:"关目商店街、超市与医疗密度够用；大型购物要去京桥或梅田。", value:"大阪市地址＋谷町线直达梅田＋京阪通勤，买家池最宽，转售韧性是本报告第一档。", risk:["站近新筑已明显溢价","国道1号沿线噪音与空气","同名车站间实际步行要核验"], pick:"站间三角区：关目高殿 ≤7 分、关目 ≤10 分；2005 年后 60–75㎡。" },
  { id:"moriguchi", rank:"02", name:"守口市 / 守口", jp:"守口市・守口", tag:"通勤性价比", color:"blue", commute:6, route:"京阪本线直达", umeda:20, scores:[9.8,8.2,8.5,8.9], price:{used:{"2LDK":[3400,4800],"3LDK":[3800,5600]},new:{"2LDK":[4200,5500],"3LDK":[4800,6500]}}, trend:9, sample:"双站步行圈；中古限定 2016 年以后，约 55–75㎡。新筑供应偏少。", life:"门真市通勤最轻松，守口市站与谷町线守口站形成双轴，适合工作日高频出勤。", commerce:"京阪百货守口店、イオンタウン守口、医院和市役所集中，生活完成度高。", value:"站前、双线与市中心边缘位置支撑流动性；价格仍低于大阪市内的关目。", risk:["京阪快急并非所有班次停靠","老旧密集街区需看防灾地图","新筑样本少，不能用单盘代表全区"], pick:"守口市站西口—守口站之间，任一站 ≤7 分；避免只靠巴士的外围。" },
  { id:"dainichi", rank:"03", name:"大日", jp:"大日", tag:"生活便利", color:"gold", commute:7, route:"大阪单轨直达", umeda:19, scores:[9.5,8.8,7.6,8.7], price:{used:{"2LDK":[3200,4400],"3LDK":[3500,5000]},new:{"2LDK":[4000,5200],"3LDK":[4400,6000]}}, trend:7, sample:"大日站步行 12 分钟内；中古限定 2016 年以后。旧塔楼另列观察。", life:"谷町线始发＋单轨直达门真市，早高峰容易坐到座位，最适合希望‘一站式生活’的家庭。", commerce:"イオンモール大日是压倒性优势，电影、餐饮、采购都能在一个街区完成。", value:"交通与商业基本盘牢，但供给体量大；同质户型较多时，楼层、朝向和管理拉开差价。", risk:["大体量社区的竞品供应","中央环状线噪音与粉尘","旧塔楼未来修缮费上行"], pick:"站东侧步行圈；优先背离中央环状线、物业费透明、长期修缮计划稳健的楼。" },
  { id:"senbayashi", rank:"04", name:"千林大宫 / 千林", jp:"千林大宮・千林", tag:"烟火气", color:"lilac", commute:13, route:"京阪本线直达", umeda:14, scores:[8.5,8.6,7.7,8.4], price:{used:{"2LDK":[3300,4500],"3LDK":[3700,5100]},new:{"2LDK":[4200,5400],"3LDK":[4800,6200]}}, trend:8, sample:"两站生活圈；10年内中古库存偏薄，新筑区间参考旭区近邻项目。", life:"千林商店街生活感很强，谷町线去梅田、京阪去门真市，适合喜欢传统大阪街区的人。", commerce:"商店街、药妆、平价餐饮密集；大型商业与高端消费相对弱。", value:"双线和大阪市门牌提供下限保护，但街区产品新旧差异大，选楼比选站更重要。", risk:["窄路与木造密集街区","新筑供应稀少导致报价跳跃","商店街附近人流与装卸噪音"], pick:"千林站与千林大宫站之间；步行去两线均不超过 10 分钟。" },
  { id:"taishibashi", rank:"05", name:"太子桥今市 / 土居", jp:"太子橋今市・土居", tag:"低总价", color:"peach", commute:9, route:"京阪本线直达", umeda:17, scores:[9.1,7.4,7.1,9.2], price:{used:{"2LDK":[3000,4200],"3LDK":[3400,4800]},new:{"2LDK":[3900,5100],"3LDK":[4400,5800]}}, trend:6, sample:"双线步行圈；新筑为稀疏样本与邻近守口项目预算带。", life:"通勤短、总价低，是功能主义者的答案；城市感和景观不如关目。", commerce:"日常采购够用，可共享守口商业；娱乐与品牌商业弱。", value:"低总价降低下跌绝对额，但产品力一般的楼盘转售速度可能慢。", risk:["淀川洪水与内涝需逐址核验","老城窄路、防灾性能分化","缺乏强地标型新盘"], pick:"太子桥今市谷町线与土居京阪之间，避开低洼一层与无充足修缮储备项目。" },
  { id:"neyagawa", rank:"06", name:"寝屋川市", jp:"寝屋川市", tag:"面积优先", color:"sand", commute:15, route:"京阪本线", umeda:32, scores:[7.8,7.8,6.2,9.6], price:{used:{"2LDK":[2700,4000],"3LDK":[3000,4500]},new:{"2LDK":[3700,4900],"3LDK":[4100,5800]}}, trend:4, sample:"寝屋川市站步行 12 分钟内；远离站点的低价库存不纳入核心判断。", life:"用通勤时间换面积，家庭型 3LDK 选择多；去梅田明显不如前五区。", commerce:"站前商场、超市与行政服务成熟，生活自足；周末进大阪市中心成本更高。", value:"站近新盘仍有需求，但人口与远郊供给让‘步行分钟数’对价格影响更大。", risk:["站远物业流动性明显下降","河川与内涝风险逐址不同","未来人口结构对需求不利"], pick:"只看站步行 ≤8 分、65–75㎡、管理良好的规模盘；不要为新筑接受 15 分钟步行。" },
  { id:"kyobashi", rank:"07", name:"京桥（补充）", jp:"京橋", tag:"城市溢价", color:"coral", commute:14, route:"京阪本线直达", umeda:7, scores:[8.3,9.7,9.5,5.8], price:{used:{"2LDK":[4800,7000],"3LDK":[5800,8500]},new:{"2LDK":[5900,7600],"3LDK":[7000,9500]}}, trend:15, sample:"京桥站步行 12 分钟内；大阪市中心溢价显著，非性价比基准。", life:"交通枢纽与夜生活最强，适合双职工和重视城市体验的人。", commerce:"京阪モール、餐饮、医疗与多线换乘密集，几乎不需要开车。", value:"买家和租客池最大，抗流动性风险强；但高买入价会压缩收益率。", risk:["夜间噪音与街区气质差异大","新筑单价显著高","短期涨幅较大，追高风险"], pick:"优先东侧住宅街与站近品牌盘；现场看夜间动线后再决定。" }
];

const projects = [
  {name:"シーンズ関目高殿 スクエアガーデン",area:"关目高殿",brand:"大阪ガス都市开发 × 京阪电铁不动产",type:"在售新筑",facts:"134户 · 站3分 · 2027年交付",price:"先着顺 5,840–7,390万",url:"https://ogud.co.jp/scenes/sekimetakadono134/outline/",hot:true},
  {name:"ウエリス大日",area:"大日",brand:"NTT都市开发系",type:"在售新筑",facts:"409户 · 谷町线始发 · 大规模",price:"3LDK预告 4,400–6,000万台",url:"https://wellith.jp/dainichi409/outline/",hot:true},
  {name:"シティタワー古川橋",area:"古川桥（邻近）",brand:"住友不动产 × 京阪电铁不动产",type:"在售Tower",facts:"41层 · 648户 · 站4分",price:"4,800–8,700万",url:"https://www.sumitomo-rd-mansion.jp/kansai/furukawabashi/",hot:true},
  {name:"パークホームズLaLa門真",area:"门真市",brand:"三井不动产Residential",type:"次新中古",facts:"2023年 · LaLaport生活圈",price:"重点观察挂牌与成交差",url:"https://www.mfr.co.jp/",hot:false},
  {name:"プラウド関目",area:"关目",brand:"野村不动产",type:"品牌中古",facts:"站近 · 大阪市内 · 家庭型",price:"10年内中古候选",url:"https://www.proud-web.jp/",hot:false},
  {name:"ジオ関目高殿",area:"关目高殿",brand:"阪急阪神不动产",type:"品牌中古",facts:"谷町线站近 · 3LDK流通",price:"逐户核验楼层与改装",url:"https://geo.8984.jp/",hot:false},
  {name:"サンマークスだいにち",area:"大日",brand:"大规模塔楼群",type:"经典Tower",facts:"多栋塔楼 · 商业直近 · 已超10年",price:"比较管理费与修缮计划",url:"https://www.homes.co.jp/mansion/chuko/osaka/dainichi_06488-st/list/",hot:false},
  {name:"守口ミッドサイト文禄ヒルズ ザ・タワー",area:"守口",brand:"站前Tower",type:"经典Tower",facts:"守口市站生活圈 · 已超10年",price:"总价友好但看长期修缮",url:"https://www.homes.co.jp/mansion/chuko/osaka/moriguchishi_06027-st/price/",hot:false},
];

const sources = [
  ["国土交通省｜令和8年地价公示","2026-03-18","官方地价趋势；住宅地连续第五年上涨","https://www.mlit.go.jp/page/kanbo01_hy_010767.html"],
  ["近畿REINS｜月度市场报告","2025-09","近畿中古公寓成交价与㎡单价口径","https://www.kinkireins.or.jp/webkanri/kanri/wp-content/uploads/2025/09/05246ffdb8bdb70379768ee9d801f9a5.pdf"],
  ["LIFULL HOME'S｜关目高殿站价格相场","2026-08查阅","70㎡全龄中古均值及十年趋势（不等于10年内价格）","https://www.homes.co.jp/mansion/chuko/osaka/sekimetakadono_06492-st/price/"],
  ["LIFULL HOME'S｜大日站价格相场","2026-08查阅","70㎡全龄中古均值与在库列表","https://www.homes.co.jp/mansion/chuko/osaka/dainichi_06488-st/price/"],
  ["SUUMO｜京阪本线新筑项目","2026-08-19抓取页","沿线在售项目与公开销售住户","https://suumo.jp/ms/shinchiku/osaka/en_keihanhonsen/"],
  ["京阪电铁不动产｜关西新筑项目","2026-08查阅","开发商项目列表、规模与交通","https://www.keihan-kiss.co.jp/mansion/kansai.php"],
];

export default function Home(){
  const [room,setRoom]=useState<Room>("3LDK");
  const [stock,setStock]=useState<Stock>("used");
  const [selected,setSelected]=useState("sekime");
  const [projectFilter,setProjectFilter]=useState("全部");
  const active=areaData.find(a=>a.id===selected) ?? areaData[0];
  const shownProjects=useMemo(()=>projects.filter(p=>projectFilter==="全部" || (projectFilter==="新筑/Tower"?p.hot:p.area.includes(projectFilter))),[projectFilter]);
  return <main>
    <nav className="topbar"><a className="brand" href="#top"><span>住</span> 大阪东线置业研究所</a><div className="navlinks"><a href="#compare">区域对比</a><a href="#detail">深度报告</a><a href="#projects">品牌楼盘</a><a href="#sources">数据来源</a></div><div className="date-pill">数据更新 · 2026.08.21</div></nav>
    <section className="hero" id="top"><div className="rail-art" aria-hidden="true"><div className="rail-line blue-line"><i/><i/><i/><i/></div><div className="rail-line red-line"><i/><i/><i/><i/><i/></div></div><div className="eyebrow"><span/> KADOMASHI COMMUTE · BUYER&apos;S FIELD GUIDE</div><h1>住得舒服，<br/><em>通勤不妥协。</em></h1><p className="hero-copy">以门真市站为圆心，沿谷町线与京阪本线，筛选大阪东部真正值得买的生活圈。价格、通勤、保值与风险，一页看清。</p><div className="hero-actions"><a className="primary" href="#compare">查看区域排名 <b>→</b></a><a className="secondary" href="#market">先看市场结论</a></div><div className="hero-stats"><div><strong>7</strong><span>个重点生活圈</span></div><div><strong>6–22<small>分</small></strong><span>门真市通勤带</span></div><div><strong>¥2,700<small>万起</small></strong><span>10年内中古预算</span></div></div></section>
    <section className="summary-strip"><span>一句话结论</span><p><b>关目高殿</b>赢在双线与保值，<b>守口</b>赢在通勤成本，<b>大日</b>赢在一站式生活。</p><i>向下探索 ↓</i></section>

    <section className="market-band" id="market"><div className="section-head"><div><div className="kicker">00 · MARKET PULSE</div><h2>价格仍向上，选择正在分化</h2></div><p>官方地价看大方向，REINS看成交，门户挂牌看当下选择。三者口径不同，本报告不混成一个“平均价”。</p></div><div className="pulse-grid"><div className="pulse-lead"><span>2026 国土交通省</span><strong>住宅地<br/>连续 5 年上涨</strong><p>全国住宅地涨幅与上年持平；大阪核心商业地涨势强，向东部住宅区传导但并不均匀。</p></div><div className="mini-chart"><h3>目标区近3年方向指数</h3>{areaData.map(a=><div className="bar-row" key={a.id}><span>{a.name.replace("（补充）","")}</span><i><b style={{width:`${30+a.trend*4}%`}}/></i><em>+{a.trend}%*</em></div>)}<small>* 由站点/行政区门户参考价与公开存量趋势归纳，仅作方向比较，不是官方成交指数。</small></div><div className="thesis"><div><b>01</b><p><strong>城市边缘优于远郊</strong>大阪市门牌与多线换乘扩大下一手买家池。</p></div><div><b>02</b><p><strong>新筑溢价已显著</strong>同面积新筑较10年内中古常高出约20–35%。</p></div><div><b>03</b><p><strong>站距决定流动性</strong>郊区尤其要把步行 8 分钟作为硬边界。</p></div></div></div></section>

    <section className="section" id="compare"><div className="section-head"><div><div className="kicker">01 · PRICE COMPASS</div><h2>把预算放到同一把尺上</h2></div><div className="controls"><div className="segmented"><button className={stock==="used"?"on":""} onClick={()=>setStock("used")}>10年内中古</button><button className={stock==="new"?"on":""} onClick={()=>setStock("new")}>新筑</button></div><div className="segmented"><button className={room==="2LDK"?"on":""} onClick={()=>setRoom("2LDK")}>2LDK</button><button className={room==="3LDK"?"on":""} onClick={()=>setRoom("3LDK")}>3LDK</button></div></div></div><div className="price-scale"><div className="scale-label"><span>2,000万</span><span>5,000万</span><span>8,000万</span><span>1亿</span></div>{areaData.map(a=>{const range=a.price[stock][room];return <button className={`range-row ${selected===a.id?"selected":""}`} onClick={()=>setSelected(a.id)} key={a.id}><span><b>{a.rank}</b>{a.name}</span><i><em style={{left:`${Math.max(0,(range[0]-2000)/80)}%`,width:`${(range[1]-range[0])/80}%`}}>{range[0].toLocaleString()}–{range[1].toLocaleString()}</em></i><small>万</small></button>})}</div><div className="method-note"><b>价格口径</b><p>2026年8月21日前后公开在库/在售价格，面积约55–75㎡，中古为2016年以后、原则上车站步行12分钟内。区间是“典型预算带”，不是最低/最高价，也不是估价保证。样本少的新筑区域结合相邻站与同生活圈项目校准。</p></div></section>

    <section className="detail-section" id="detail"><div className="detail-tabs" role="tablist" aria-label="选择区域">{areaData.map(a=><button role="tab" aria-selected={selected===a.id} className={selected===a.id?"on":""} onClick={()=>setSelected(a.id)} key={a.id}><small>{a.rank}</small>{a.name}</button>)}</div><div className={`detail-panel ${active.color}`}><div className="detail-title"><div><span>{active.jp}</span><h2>{active.name}</h2><p>{active.tag}</p></div><div className="big-time"><strong>{active.commute}</strong><span>分钟左右<br/>至门真市</span></div></div><div className="score-grid">{["通勤","生活","保值","性价比"].map((label,i)=><div key={label}><span>{label}</span><b>{active.scores[i]}</b><i><em style={{width:`${active.scores[i]*10}%`}}/></i></div>)}</div><div className="detail-copy"><article><span>COMMUTE</span><h3>通勤与动线</h3><p><b>{active.route}</b>；到门真市约 {active.commute} 分钟。到东梅田/梅田核心约 {active.umeda} 分钟（均为典型时段估算，含候车/换乘波动）。</p></article><article><span>LIFE</span><h3>生活与商业</h3><p>{active.life}</p><p>{active.commerce}</p></article><article><span>VALUE</span><h3>保值逻辑</h3><p>{active.value}</p></article><article className="risk"><span>WATCH</span><h3>买前风险</h3><ul>{active.risk.map(r=><li key={r}>{r}</li>)}</ul></article></div><div className="buy-box"><span>我的搜索条件</span><strong>{active.pick}</strong><small>{active.sample}</small></div></div></section>

    <section className="section projects" id="projects"><div className="section-head"><div><div className="kicker">03 · PROJECT WATCHLIST</div><h2>大手品牌与地标盘</h2></div><p>“值得关注”不等于“值得追价”。新筑看定价与供应，中古看管理、修缮和真实成交。</p></div><div className="filter-pills">{["全部","新筑/Tower","关目","大日","守口"].map(f=><button key={f} onClick={()=>setProjectFilter(f)} className={projectFilter===f?"on":""}>{f}</button>)}</div><div className="project-list">{shownProjects.map((p,i)=><a href={p.url} target="_blank" rel="noreferrer" className="project-row" key={p.name}><span className="project-no">{String(i+1).padStart(2,"0")}</span><div><small>{p.area} · {p.type}</small><h3>{p.name}</h3><p>{p.brand}</p></div><div className="project-facts"><span>{p.facts}</span><strong>{p.price}</strong></div><b className="open">↗</b></a>)}</div><div className="brand-note"><b>品牌筛选原则</b><span>优先观察三井、住友、野村、阪急阪神、京阪等具备持续管理与流通认知的项目；但郊区住宅的决定因素仍是站距、总价与长期修缮，不应只为品牌多付钱。</span></div></section>

    <section className="decision"><div><div className="kicker">04 · FINAL CALL</div><h2>三种人，三种答案</h2></div><div className="decision-cards"><article><span>A</span><h3>要全能与保值</h3><strong>选关目高殿 / 关目</strong><p>接受更高入场价，换取大阪市地址、双线和更宽买家池。</p></article><article><span>B</span><h3>每天去门真市</h3><strong>选守口市 / 守口</strong><p>通勤摩擦最低，商业成熟，预算比关目更友好。</p></article><article><span>C</span><h3>想要大房与商场</h3><strong>选大日</strong><p>始发站、单轨、イオンモール；严选朝向与管理即可。</p></article></div></section>

    <section className="sources section" id="sources"><div className="section-head"><div><div className="kicker">05 · SOURCES & NOTES</div><h2>可核验的数据来源</h2></div><p>来源页面会随销售与挂牌变化。建议看房当天再次打开项目概要，确认销售期、户型、管理费与交付时间。</p></div><div className="source-table">{sources.map((s,i)=><a href={s[3]} target="_blank" rel="noreferrer" key={s[0]}><b>{String(i+1).padStart(2,"0")}</b><span><strong>{s[0]}</strong><small>{s[2]}</small></span><time>{s[1]}</time><em>↗</em></a>)}</div><div className="disclaimer"><strong>阅读说明</strong><p>本页用于缩小搜房范围，不构成投资、贷款、税务或法律建议。通勤时间为典型路线估算；价格受面积、楼层、朝向、装修、管理状态影响很大。灾害风险必须在国土交通省ハザードマップ与各市公开地图中逐址核验。</p></div></section>
    <footer><div className="brand"><span>住</span> 大阪东线置业研究所</div><p>门真市通勤购房地图 · 最后整理 2026.08.21</p><a href="#top">回到顶部 ↑</a></footer>
  </main>
}
