"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import CachedPropertyMap, { type CachedRouteTarget } from "./cached-property-map";
import { type CatalogProperty, getHeroAsset } from "./catalog-data";

type CatalogCache = {
  generatedAt:string; origin:{name:string;lat:number;lng:number};
  facilitySummary:{total:number;convenienceStores:number;supermarkets:number;sports:number;transit:number};
  facilities:Array<{name:string;label:string;iconType:string;category:string;vicinity?:string;lat:number;lng:number}>;
  routes:Record<string,{provider?:string;name?:string;mode?:string;durationMinutes?:number}>;
};
const sections=[["overview","概览"],["plans","户型价格"],["design","设计"],["parking","停车"],["map","地图"],["commute","通勤"],["life","生活"],["sports","运动"],["value","投资判断"]] as const;

function routeMode(value?:string):CachedRouteTarget["mode"]{const mode=value?.toUpperCase();return mode==="WALKING"||mode==="DRIVING"||mode==="TRANSIT"?mode:"TRANSIT"}

export default function CatalogPropertyPage({data,cache}:{data:CatalogProperty;cache:CatalogCache}){
  const scrollRoot=useRef<HTMLElement|null>(null);const[active,setActive]=useState("overview");const hero=getHeroAsset(data.slug);
  const routeTargets=useMemo(()=>Object.entries(cache.routes).map(([id,route])=>({id,provider:route.provider==="ekispert"?"ekispert" as const:"google" as const,name:route.name??id,sub:route.provider==="ekispert"?"Ekispert公共交通缓存":routeMode(route.mode)==="WALKING"?"步行缓存":"驾车缓存",mode:routeMode(route.mode)})),[cache.routes]);
  useEffect(()=>{const root=scrollRoot.current;if(!root)return;const observer=new IntersectionObserver(entries=>entries.forEach(entry=>entry.isIntersecting&&setActive(entry.target.id)),{root,threshold:.5});sections.forEach(([id])=>{const node=document.getElementById(id);if(node)observer.observe(node)});return()=>observer.disconnect()},[]);
  return <main className="property-page catalog-theme" ref={scrollRoot}>
    <aside className="story-nav" aria-label="页面目录"><a className="story-brand" href="../../"><span>住</span><b>大阪置业研究所</b></a><div className="story-progress"><i style={{width:`${((sections.findIndex(([id])=>id===active)+1)/sections.length)*100}%`}}/></div><nav>{sections.map(([id,label],index)=><a key={id} className={active===id?"active":""} href={`#${id}`}><small>{String(index+1).padStart(2,"0")}</small>{label}</a>)}</nav><a className="back-link" href="../../#projects">← 返回推荐物件</a></aside>
    <section className="story-section hero-story" id="overview">{hero?<img className="hero-image" src={hero} alt={`${data.name}资料主图`}/>:<div className="catalog-hero-art"><span>{data.station}</span></div>}<div className="hero-shade"/><div className="story-copy hero-copy-block"><p className="story-kicker">FULL RESEARCH · {data.roman}</p><h1>{data.headline}</h1><p className="story-lead">{data.lead}</p><div className="hero-facts">{data.facts.map(([value,label])=><span key={label}><b>{value}</b>{label}</span>)}</div></div><a className="image-credit" href={data.source} target="_blank" rel="noreferrer">资料与图片来源：{data.sourceLabel} ↗</a></section>
    <section className="story-section concept-story"><div className="story-copy centered-copy"><p className="story-kicker">POSITIONING · {data.area}</p><h2>{data.name}<br/>值不值得进入看房名单？</h2><p>{data.concept}</p><div className="showcase-score">{data.scores.map(([label,value])=><span key={label}><b>{value}</b>{label}</span>)}</div><div className="verdict-row"><article><b>当前状态</b><span>{data.status}</span></article><article><b>土地与权利</b><span>{data.rights??"所有权；中古物件仍需从登记与重要事项说明逐户确认"}</span></article></div></div></section>
    <section className="story-section plans-story catalog-section" id="plans"><div className="story-copy wide-copy"><p className="story-kicker">PRICE & PLAN · 2026.08 SNAPSHOT</p><div className="section-title-row"><h2>价格只是入口，户型与持有成本才是答案。</h2><div className="price-display"><small>{data.priceSub}</small><b>{data.price}</b></div></div><div className="catalog-plan-grid">{data.plans.map(plan=><article key={plan.name+plan.tag}><small>{plan.tag}</small><h3>{plan.name}</h3><p>{plan.spec}</p><strong>{plan.price}</strong><span>{plan.note}</span></article>)}</div><p className="catalog-data-note">{data.priceNote} 新筑价格以最新物件概要为准；中古挂牌不等于成交，且同一住户可能在多个平台重复出现。</p></div></section>
    <section className="story-section catalog-design" id="design"><div className="story-copy wide-copy catalog-design-grid"><div><p className="story-kicker">DESIGN & DUE DILIGENCE</p><h2>不只看效果图，<br/>也看十年后的维护。</h2><p>本页把设计理解为建筑体量、归家动线、住户规模和未来修缮，而不是只评价外观。</p></div><div><div className="catalog-design-number">{data.facts[0][0]}</div><ul>{data.design.map(item=><li key={item}>{item}</li>)}</ul></div></div></section>
    <section className="story-section parking-story" id="parking"><div className="story-copy wide-copy"><p className="story-kicker">PARKING & MOBILITY</p><h2>车位要按“现在能不能用”判断。</h2><div className="parking-grid">{data.parking.map(([value,label,note])=><article key={label}><strong>{value}</strong><h3>{label}</h3><p>{note}</p></article>)}</div><div className="parking-advice"><b>统一核验清单</b><ol><li>当前空位、候补顺序与住户抽签规则</li><li>机械位车高、车宽、重量和充电条件</li><li>周边月租替代与夜间回家动线</li><li>设备更新是否已经进入长期修缮预算</li></ol></div></div></section>
    <section className="story-section map-story" id="map"><CachedPropertyMap cache={cache} routeTargets={routeTargets} title={data.name}/></section>
    <section className="story-section commute-story" id="commute"><div className="story-copy wide-copy"><p className="story-kicker">COMMUTE LOGIC</p><h2>把每天发生的摩擦，逐段拆开。</h2><div className="commute-flow">{data.commute.map(([place,time,note])=><article key={place}><small>{place}</small><strong>{time}</strong><p>{note}</p></article>)}</div><p className="callout">地图按钮展示开发阶段查询并保存的路线快照，不会在点击时调用Ekispert或Google Directions。班次与拥堵会变化，出发前仍应复核。</p></div></section>
    <section className="story-section life-story" id="life"><div className="story-copy wide-copy"><p className="story-kicker">DAILY LIFE</p><h2>便利店、超市与大型商业，一个都不能只看数量。</h2><div className="life-grid">{data.life.map(([place,role,note])=><article key={place}><b>{role}</b><h3>{place}</h3><p>{note}</p></article>)}</div><p className="callout dark">地图已标出最近7家便利店、8家超市及主要生活设施，并直接显示名称。看房仍建议在工作日晚间走一次真实采购路线。</p></div></section>
    <section className="story-section sports-story" id="sports"><div className="story-copy wide-copy"><p className="story-kicker">BADMINTON, POOL & SPORTS</p><h2>体育馆不是附注，而是生活半径的一部分。</h2><div className="sports-focus"><article className="sport-primary"><small>{data.sports.time}</small><h3>{data.sports.primary}</h3><strong>主要运动设施</strong><p>{data.sports.detail}</p></article><div className="sport-list">{data.sports.others.map(([name,note])=><article key={name}><b>{name}</b><span>{note}</span></article>)}</div></div><p className="showcase-note">每套地图收录12个大阪东部主要体育设施；公共馆羽毛球开放取决于团体预约与个人利用时段。</p></div></section>
    <section className="story-section value-story" id="value"><div className="story-copy wide-copy"><p className="story-kicker">VALUE & FUTURE</p><h2>把支撑因素和折价因素放在同一页。</h2><div className="value-matrix"><article className="positive"><small>支撑因素</small><ul>{data.positive.map(item=><li key={item}>{item}</li>)}</ul></article><article className="negative"><small>需要折价思考</small><ul>{data.negative.map(item=><li key={item}>{item}</li>)}</ul></article></div><div className="final-verdict"><span>研究所判断</span><h3>{data.verdict}</h3><p>最终出价应以目标住户的登记、管理规约、长期修缮计划、重要事项调查报告、灾害地图和近期真实成交为准。</p></div><div className="source-links"><a href={data.source} target="_blank" rel="noreferrer">{data.sourceLabel} ↗</a></div><p className="fine-print">信息更新至2026年8月公开资料。页面用于缩小看房范围，不构成投资、贷款、税务或法律建议；地图设施和路线为开发阶段缓存快照。</p></div></section>
  </main>;
}
