"use client";

import { useEffect, useRef, useState } from "react";
import CachedPropertyMap, { type CachedRouteTarget } from "../cached-property-map";
import mapCache from "./map-cache.json";

const official = "https://wellith.jp/dainichi409/";
const assetRoot = "../../assets/wellith-dainichi";
const images = {
  hero:`${assetRoot}/hero.webp`, design:`${assetRoot}/design.webp`, entrance:`${assetRoot}/entrance.webp`, lounge:`${assetRoot}/lounge.webp`, fitness:`${assetRoot}/fitness.webp`,
  sj:`${assetRoot}/plan-sj.png`, sb:`${assetRoot}/plan-sb.png`, wj:`${assetRoot}/plan-wj.png`,
};
const sections = [["overview","概览"],["plans","户型价格"],["design","设计"],["parking","停车"],["map","地图"],["commute","通勤"],["life","生活"],["sports","运动"],["value","投资判断"]] as const;
const routeTargets = [
  {id:"kadomashi",provider:"ekispert",name:"门真市",sub:"大阪单轨",mode:"TRANSIT"},{id:"kyobashi",provider:"ekispert",name:"京桥",sub:"地铁 / 京阪方向",mode:"TRANSIT"},{id:"osaka",provider:"ekispert",name:"梅田 / 大阪站",sub:"谷町线直达东梅田",mode:"TRANSIT"},{id:"honmachi",provider:"ekispert",name:"本町",sub:"核心办公区",mode:"TRANSIT"},{id:"namba",provider:"ekispert",name:"难波",sub:"南部商业中心",mode:"TRANSIT"},{id:"shin-osaka",provider:"ekispert",name:"新大阪",sub:"新干线门户",mode:"TRANSIT"},{id:"itami",provider:"ekispert",name:"大阪伊丹机场",sub:"单轨方向",mode:"TRANSIT"},{id:"kansai",provider:"ekispert",name:"关西机场",sub:"铁路换乘",mode:"TRANSIT"},
  {id:"dainichi",provider:"google",name:"大日站",sub:"步行",mode:"WALKING"},{id:"kadoma-gym",provider:"google",name:"门真综合体育馆",sub:"羽毛球 · 驾车",mode:"DRIVING"},{id:"ractab",provider:"google",name:"RACTAB Dome",sub:"泳池 / 体育 · 驾车",mode:"DRIVING"},{id:"moriguchi-gym",provider:"google",name:"守口市民体育馆",sub:"羽毛球 · 驾车",mode:"DRIVING"},
] satisfies CachedRouteTarget[];

export default function WellithDainichi(){
  const scrollRoot=useRef<HTMLElement|null>(null);const[activeSection,setActiveSection]=useState("overview");
  useEffect(()=>{const root=scrollRoot.current;if(!root)return;const observer=new IntersectionObserver(entries=>entries.forEach(entry=>entry.isIntersecting&&setActiveSection(entry.target.id)),{root,threshold:.5});sections.forEach(([id])=>{const node=document.getElementById(id);if(node)observer.observe(node)});return()=>observer.disconnect()},[]);
  return <main className="property-page wellith-theme" ref={scrollRoot}>
    <aside className="story-nav" aria-label="页面目录"><a className="story-brand" href="../../"><span>住</span><b>大阪置业研究所</b></a><div className="story-progress"><i style={{width:`${((sections.findIndex(([id])=>id===activeSection)+1)/sections.length)*100}%`}}/></div><nav>{sections.map(([id,label],i)=><a key={id} className={activeSection===id?"active":""} href={`#${id}`}><small>{String(i+1).padStart(2,"0")}</small>{label}</a>)}</nav><a className="back-link" href="../../#projects">← 返回推荐物件</a></aside>

    <section className="story-section hero-story" id="overview"><img className="hero-image" src={images.hero} alt="Wellith大日外观完成预想图"/><div className="hero-shade"/><div className="story-copy hero-copy-block"><p className="story-kicker">PROPERTY 03 · DAINICHI</p><h1>409户社区，<br/><em>一整套生活系统。</em></h1><p className="story-lead">步行11分钟不是站前盘，但它用70.9%车位覆盖、7类公共空间、AEON Mall与谷町线始发站，换来更完整的家庭日常。三套优选中，这是“住得最像一个新社区”的一套。</p><div className="hero-facts"><span><b>409</b>户</span><span><b>11</b>分钟到站</span><span><b>290</b>车位</span><span><b>2028.04</b>预计交付</span></div></div><a className="image-credit" href={official} target="_blank" rel="noreferrer">图片：Wellith大日官方网站完成预想图 ↗</a></section>

    <section className="story-section concept-story"><div className="story-copy centered-copy"><p className="story-kicker">THE BIG IDEA</p><h2>用多走八分钟，<br/>换车位、商场与社区设施。</h2><p>大日站连接谷町线和大阪单轨，AEON Mall大日约620m。项目不是靠一个户型取胜，而是把住宅、车位、自行车、共享空间和周末采购放进同一套系统。它更适合家庭长期住，不适合只追求最短站距的人。</p><div className="showcase-score"><span><b>8.5</b>通勤</span><span><b>9.5</b>家庭生活</span><span><b>8.2</b>停车</span><span><b>8.3</b>买入性价比</span></div><div className="verdict-row"><article><b>最强项</b><span>大规模配套、商场、始发站与接近七成的车位覆盖</span></article><article><b>核心风险</b><span>站距11分钟、409户同质供应、共用设施长期维护</span></article></div></div></section>

    <section className="story-section plans-story" id="plans"><div className="story-copy wide-copy"><p className="story-kicker">PRICE & PLAN · 2026.08</p><div className="section-title-row"><h2>51种户型，真正的选择是“总价、储物与朝向”。</h2><div className="price-display"><small>当前广告口径</small><b>4,400</b><span>万台起 · 3LDK</span></div></div><div className="plan-grid"><article><img src={images.sj} alt="SJ户型图"/><div><small>入门家庭型</small><h3>SJ · 3LDK</h3><p>63.22㎡</p><strong>4千万中后段起参考</strong><span>控制总价，适合三口之家；要仔细看房间宽度、柱位与储物是否够长期使用。</span></div></article><article className="recommended"><img src={images.sb} alt="SB户型图"/><div><small>研究所优先关注</small><h3>SB · 3LDK</h3><p>66.49㎡</p><strong>当前公开住户约5,679万</strong><span>面积与总价处在主流家庭买家区间。相比高楼层，更应优先安静朝向与有效储物。</span></div></article><article><img src={images.wj} alt="WJ户型图"/><div><small>长期自住升级</small><h3>WJ · 3LDK</h3><p>75.43㎡</p><strong>首期公开上限约6,909万</strong><span>面积稀缺、适合长期家庭生活；转售时总价更高，需用楼层、朝向和户型完整度支撑。</span></div></article></div><div className="cost-strip"><span>首期公开范围 <b>4,159–6,909万</b></span><span>管理费 <b>约1.04–1.39万/月</b></span><span>修缮积立金 <b>约0.65–0.87万/月</b></span><small>不同销售期与住户价格会变化；修缮积立金早期较低不代表长期不涨，应阅读长期修缮计划和阶段调价表。</small></div></div></section>

    <section className="story-section design-story" id="design"><div className="split-visual"><img src={images.design} alt="Wellith大日外观设计完成预想图"/><div className="story-copy"><p className="story-kicker">DESIGN LANGUAGE</p><h2>不是孤立的大楼，而是409户的内向型社区。</h2><p>14层体量围绕入口、庭院和共用空间展开。外观的横向节奏与植栽强调家庭住宅感，重点在“每天怎么经过”，而不是制造一座远眺地标。</p><ul><li>13,656.97㎡大基地，形成较完整的社区动线</li><li>主入口与车行入口分离，减少日常交叉</li><li>共享空间集中，适合儿童与远程办公家庭</li><li>大规模同时意味着管理规则、噪音与预约竞争更复杂</li></ul></div></div></section>

    <section className="story-section amenity-story"><div className="amenity-gallery"><figure><img src={images.entrance} alt="入口完成预想图"/><figcaption>Entrance · 大社区归家界面</figcaption></figure><figure><img src={images.lounge} alt="公共休息室完成预想图"/><figcaption>Cafe / Library Lounge</figcaption></figure><figure><img src={images.fitness} alt="健身空间完成预想图"/><figcaption>Fitness Room</figcaption></figure></div><div className="story-copy compact-copy"><p className="story-kicker">SEVEN COMMON SPACES</p><h2>这些空间有价值，前提是你真的会用。</h2><p>休息室、客房、咖啡休息室、儿童/图书空间、派对室、健身房与庭院组成7类共享空间，另有无人商店与工作空间概念。签约前要问收费、预约上限、访客规则、开放时间和未来翻新预算。</p></div></section>

    <section className="story-section parking-story" id="parking"><div className="story-copy wide-copy"><p className="story-kicker">PARKING & MOBILITY</p><h2>290个车位，是大日家庭生活最硬的配置之一。</h2><div className="parking-grid"><article><strong>290</strong><h3>汽车</h3><p>186机械＋104平置（含访客等）</p><b>5,000–15,000日元/月</b></article><article><strong>818</strong><h3>自行车</h3><p>其中368个Cycle Port区画</p><b>家庭多车更友好</b></article><article><strong>31</strong><h3>摩托 / 小型摩托</h3><p>大规模住区仍属有限资源</p><b>确认抽签与使用尺寸</b></article></div><div className="parking-advice"><b>车位判断重点</b><ol><li>平置位与机械位的抽签分组是否不同</li><li>EV充电位数量、使用费与轮换机制</li><li>高峰出入口是否受周边商场车流影响</li><li>机械设备更新成本如何计入长期修缮</li></ol></div></div></section>

    <section className="story-section map-story" id="map"><CachedPropertyMap cache={mapCache} routeTargets={routeTargets} title="Wellith 大日"/></section>

    <section className="story-section commute-story" id="commute"><div className="story-copy wide-copy"><p className="story-kicker">COMMUTE LOGIC</p><h2>去门真非常快，去梅田靠始发站降低摩擦。</h2><div className="commute-flow"><article><small>HOME → 大日</small><strong>步行约11–13分钟</strong><p>官方11分钟，缓存步行约13分钟；雨天与红绿灯需实测。</p></article><article><small>大日 → 门真市</small><strong>缓存约10分钟</strong><p>大阪单轨方向，适合高频门真通勤。</p></article><article><small>大日 → 东梅田</small><strong>谷町线始发</strong><p>运行约19分钟级，页面到大阪站缓存约30分钟。</p></article><article><small>大日 → 伊丹机场</small><strong>缓存约43分钟</strong><p>单轨同线方向是明显优势，仍需核对班次。</p></article></div><p className="callout">“始发站能坐到座位”对长期通勤的价值很高，但11分钟步行也会每天发生。建议在工作日早8点和晚8点各走一次，从实际住栋位置到站台计时。</p></div></section>

    <section className="story-section life-story" id="life"><div className="story-copy wide-copy"><p className="story-kicker">DAILY LIFE</p><h2>AEON Mall是主轴，周边超市和便利店负责补全日常。</h2><div className="life-grid"><article><b>约620m</b><h3>AEON Mall大日</h3><p>约8分钟步行，生鲜、餐饮、影院、服饰与亲子需求可一次完成。</p></article><article><b>7家</b><h3>近邻便利店</h3><p>地图收录周边最近门店并显示名称，夜间补给不依赖商场营业时间。</p></article><article><b>8家</b><h3>超市选择</h3><p>除AEON外，周边食品超市形成价格与闭店时间上的替代。</p></article><article><b>社区内</b><h3>健身 / 儿童 / 工作</h3><p>共享空间减少部分外出，但不能替代公共体育馆与真正的餐饮街区。</p></article></div><p className="callout dark">大日的便利高度集中在商场。优点是雨天与家庭周末高效；风险是生活风格较单一。看房时应顺路检查商场闭店后的步行环境和住宅附近晚间餐饮。</p></div></section>

    <section className="story-section sports-story" id="sports"><div className="story-copy wide-copy"><p className="story-kicker">BADMINTON, POOL & SPORTS</p><h2>门真体育馆与RACTAB Dome构成东侧运动双核心。</h2><div className="sports-focus"><article className="sport-primary"><small>地图缓存 · 驾车约4分钟</small><h3>门真市立综合体育馆</h3><strong>副馆可布置3面羽毛球场</strong><p>距离近，适合作为主要打球场地。个人利用仍取决于团体预约空档，应提前研究门真市的预约系统与注册规则。</p><a href="https://information.konamisportsclub.jp/trust/kadoma/" target="_blank" rel="noreferrer">查看官方设施信息 ↗</a></article><div className="sport-list"><article><b>RACTAB Dome</b><span>缓存驾车约13分钟 · 泳池 / 竞技场 / 冰场</span></article><article><b>守口市民体育馆</b><span>缓存驾车约11分钟 · 羽毛球备选</span></article><article><b>鹤见体育中心</b><span>大阪市公共馆 · 驾车轮换选择</span></article><article><b>寝屋川 / 大东</b><span>东部公共馆网络 · 比赛与团体预约备选</span></article></div></div><p className="showcase-note">地图共缓存12个体育设施。页面点击仅绘制已经查询好的路线，不触发Ekispert、Google Directions或地点搜索请求。</p></div></section>

    <section className="story-section value-story" id="value"><div className="story-copy wide-copy"><p className="story-kicker">VALUE & FUTURE</p><h2>最适合长期家庭自住，投资判断要防“同质供给”。</h2><div className="value-matrix"><article className="positive"><small>支撑因素</small><ul><li>谷町线始发＋大阪单轨，门真、梅田、伊丹各有清晰路线</li><li>AEON Mall与大规模共享空间提升家庭自住黏性</li><li>290个车位和818个自行车位符合郊区家庭使用</li><li>4千万台起的3LDK，相比大阪市内站近新筑更可控</li></ul></article><article className="negative"><small>需要折价思考</small><ul><li>11分钟站距是转售时无法改变的硬条件</li><li>409户会在同一时期形成相似二手挂牌竞争</li><li>7类共用设施与机械停车需要持续维护</li><li>准工业地域周边环境、道路噪音与景观需逐户确认</li></ul></article></div><div className="final-verdict"><span>研究所判断</span><h3>适合有车、重视商场与运动、计划住满7年以上的家庭。</h3><p>优先66–75㎡、安静朝向且靠近顺手出入口的3LDK。若只住3–5年或每天必须快速进大阪市中心，关目高殿的站距与流动性更强；若长期自住，大日的空间与配套更完整。</p></div><div className="source-links"><a href={`${official}outline/`} target="_blank" rel="noreferrer">官方物件概要 ↗</a><a href={`${official}plan/`} target="_blank" rel="noreferrer">官方户型资料 ↗</a><a href={`${official}commonspace/`} target="_blank" rel="noreferrer">官方公共空间 ↗</a></div><p className="fine-print">本页为中文置业研究，不构成投资、贷款、税务或法律建议。价格更新至2026年8月公开资料；地图设施和路线为开发阶段缓存快照，商户、班次与开放时间会变化，请在看房和签约当天复核。</p></div></section>
  </main>;
}
